"""Video-learning domain API."""

from .invidious_account import (
    begin_invidious_account_authorization,
    complete_invidious_account_authorization,
    disconnect_invidious_account,
    invidious_account_status,
    invidious_redirect_uri,
)
from .marks import (
    MARK_AUTHORS,
    MARK_KINDS,
    MarkNotFound,
    create_mark,
    delete_mark,
    get_mark,
    marks_list,
    normalize_mark,
    suggest_marks,
    update_mark,
)
from .service import (
    PROVIDER_RESOLVERS,
    ProviderResolution,
    TimedMediaError,
    TimedMediaNotFound,
    TimedMediaStore,
    build_segments,
    get_timed_media_store,
    load_video_learning_settings,
    material_with_playback,
    normalize_cues,
    parse_youtube_url,
    refresh_invidious_transcript,
    resolve_material,
    save_video_learning_settings,
    test_invidious_connection,
)

__all__ = [
    "PROVIDER_RESOLVERS",
    "ProviderResolution",
    "TimedMediaError",
    "TimedMediaNotFound",
    "TimedMediaStore",
    "build_segments",
    "begin_invidious_account_authorization",
    "complete_invidious_account_authorization",
    "disconnect_invidious_account",
    "get_timed_media_store",
    "invidious_account_status",
    "invidious_redirect_uri",
    "load_video_learning_settings",
    "material_with_playback",
    "normalize_cues",
    "parse_youtube_url",
    "refresh_invidious_transcript",
    "resolve_material",
    "save_video_learning_settings",
    "test_invidious_connection",
    "MARK_AUTHORS",
    "MARK_KINDS",
    "MarkNotFound",
    "create_mark",
    "delete_mark",
    "get_mark",
    "marks_list",
    "normalize_mark",
    "suggest_marks",
    "update_mark",
]
