export {
  addGitHubSource,
  addWebSource,
  linkFolder,
  cancelWebSourceSync,
  listGitHubSources,
  listLinkedFolders,
  listWebSources,
  listWebSourceSyncJobs,
  removeGitHubSource,
  removeWebSource,
  retryWebSourceSync,
  syncGitHubSources,
  syncLinkedFolder,
  syncWebSources,
  unlinkFolder,
  updateWebSourceSchedule,
} from "./client";

export type {
  AddGitHubSourcePayload,
  AddWebSourcePayload,
  GitHubSource,
  GitHubSyncResult,
  LinkedFolderInfo,
  WebSource,
  WebSourceSchedulePayload,
  WebSourceSyncJob,
  WebSyncResult,
  WebSyncSourceResult,
} from "../model/types";
